### ISSUE TITLE
running time of Pando

### ISSUE THREAD

**Issue by crystal0721** [quadbio/Pando#39]
Dears,  thanks for this great  packages.  How much time is required to analyze using this software? We have analyzed about 2000 cells and have been analyzing for a week, currently stuck at the infer_grn step. Is there any way to speed up the analysis process?

   Thanks very much.

**Comment by joschif** [comment]
Dear @crystal0721, for 2k cells it should not take this long, but it also heavily depends on the number of features Pando uses. In our analysis we subset the peaks and genes to be used by pando. Especially for the peaks ATAC datasets can be very large and feature selection here speeds up the running time by a lot. Moreover I'd recommend parallelizing on multiple cores if possible. E.g. we have run Pando on ~100k cells with 8 cores in just over 6 hours before
