### ISSUE TITLE
Run pando on dataset with different conditions

### ISSUE THREAD

**Issue by JoreVW** [quadbio/Pando#43]
Hi, thank you for this tool, I'm starting to use it on my multimodal data and everything seems to be working fine. I have a question on the use on my dataset though. My dataset contains 2 conditions, Ctrl and KO. Do I run Pando separately on each of the conditions (so generating 2 SeuratPlus objects) and just compare whether networks are more or less present. Or do I run it on my complete dataset and is there than a way to compare between my 2 conditions?

**Comment by joschif** [comment]
Hi @JoreVW, sorry for the late reply. You can do both in principle, although my preference is either inference on the complete dataset or just on the control and then assessing differential expression/accessibility or the network genes/modules/regulatory regions. In general I think that's more reliable than quantitatively comparing two entirely separate networks.
