### ISSUE TITLE
Question: celltype-specific GRN

### ISSUE THREAD

**Issue by tkisss** [quadbio/Pando#49]
Hi, thanks for this tool. 

I want to know if Pando could infer celltype-specific GRNs?  Can I  gain the celltype-specific GRNs by performing Pando on a specific celltype?

**Comment by joschif** [comment]
Hi @tkisss, that would be one way to to that, although I generally prefer to infer the GRN on all data and then filter it by celltype-specific accessibility/expression to create celltype-specific GRNs. Essentially that requires filtering the GRN graph for edges (regulatory regions) and/or nodes (genes) that are accessible/expressed in a certain celltype.

**Comment by RaghadShu** [comment]
Hello, 
I'm not the original author but I have a followup:
Would simply subsetting the initial Seurat object per cluster (cell-type) and then running the Pando workflow per cluster be sufficient to accomplish this?

Thanks,
Raghad
